spring:
  application:
    name: sharding-jdbc-demo
  shardingsphere:
    # 内存模式
    mode:
      type: Memory
    # 打印SQl
    props:
      sql-show: true
    #数据源配置
    datasource:
      names: master,slave1,slave2
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        jdbc-url: "jdbc:mysql://101.34.45.104:3306/db_user?characterEncoding=utf-8&useSSL=false"
        username: "root"
        password: "03790379"
      slave1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        jdbc-url: "jdbc:mysql://101.34.45.104:3307/db_user?characterEncoding=utf-8&useSSL=false"
        username: "root"
        password: "03790379"
      slave2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        jdbc-url: "jdbc:mysql://101.34.45.104:3308/db_user?characterEncoding=utf-8&useSSL=false"
        username: "root"
        password: "03790379"
    rules:
      # 读写分离配置
      readwrite-splitting:
        data-sources:
          load-balancers:
            roundRobin:
              # 负载均衡 轮询算法
              type: ROUND_ROBIN
          # 自定义名称
          master-slave:
            props:
              # 自动感知数据源名称
              auto-aware-data-source-name: master
              # 负载均衡算法名称
              load-balancer-name: roundRobin
              # 写数据源名称
              write-data-source-name: master
              # 读数据源名称
              read-data-source-names: slave1,slave2
            # 读写分离类型
            type: Static