spring:
  application:
    name: sharding-jdbc-demo
  shardingsphere:
    # 内存模式
    mode:
      type: Memory
    # 打印SQl
    props:
      sql-show: true
    # 数据源配置
    datasource:
      names: server-user,server-order
      server-user:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        jdbc-url: "jdbc:mysql://101.34.45.104:3301/db_user?characterEncoding=utf-8&useSSL=false"
        username: "root"
        password: "03790379"
      server-order:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: "com.mysql.cj.jdbc.Driver"
        jdbc-url: "jdbc:mysql://101.34.45.104:3302/db_order?characterEncoding=utf-8&useSSL=false"
        username: "root"
        password: "03790379"
    rules:
      # 分片
      sharding:
        tables:
          # 配置实际访问数据节点
          t_user:
            actual-data-nodes: server-user.t_user
          t_order:
            actual-data-nodes: server-order.t_order